feat(deps): Upgrade functionaltest-system to 1.0.1
Bug: b/402510457
Change-Id: I562094619a3ad8ab0624ab4c8280c1e8d2eb2a7e
GitOrigin-RevId: 7e4cbad37861b8d6a484d20bba38ce79416afe1f

diff --git a/testing/functionaltest-system/bazel/ghz_test_runner b/testing/functionaltest-system/bazel/ghz_test_runner
--- a/testing/functionaltest-system/bazel/ghz_test_runner
+++ b/testing/functionaltest-system/bazel/ghz_test_runner
@@ -1,4 +1,17 @@
 #!/bin/bash
+# Copyright 2025 Google LLC
+#
+# Licensed under the Apache License, Version 2.0 (the "License");
+# you may not use this file except in compliance with the License.
+# You may obtain a copy of the License at
+#
+#      http://www.apache.org/licenses/LICENSE-2.0
+#
+# Unless required by applicable law or agreed to in writing, software
+# distributed under the License is distributed on an "AS IS" BASIS,
+# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
+# See the License for the specific language governing permissions and
+# limitations under the License.
 
 set -o errexit
 
@@ -10,43 +23,60 @@ function usage() {
 usage:
   $0 <options>
     --endpoint-hostport <host:port> host:port string
-    --docker-network <name>         docker network
     --protoset <filename>           protobuf spec image file
     --rpc <rpc name>                rpc name
     --request <filename>            request.json filename
     --plaintext                     send plaintext request
+    --config-file                   ghz config json file
 environment variables:
-    TEST_TOOLS_IMAGE                docker image uri for test tools
+    GHZ                             path to ghz executable (required)
 USAGE
   # shellcheck disable=SC2086
   exit ${exitval}
 }
 
+function check_app() {
+  declare -n _app=$1
+  if [[ -z ${_app} ]]; then
+    printf "env var [%s] is not set\n" "$1" &>/dev/stderr
+    exit 1
+  elif ! command -v "${_app}" >/dev/null; then
+    printf "%s command [%s] not found or not executable\n" "$1" "${_app}" &>/dev/stderr
+    exit 1
+  fi
+}
+
+check_app GHZ
+
 while [[ $# -gt 0 ]]; do
   case "$1" in
     --endpoint-hostport)
       ENDPOINT_HOSTPORT="$2"
-      shift 2
+      shift 2 || usage 1
       ;;
     --docker-network)
-      DOCKER_NETWORK="$2"
-      shift 2
+      printf "Ignoring arg --docker-network\n"
+      shift 2 || usage 1
       ;;
     --rpc)
       RPC="$2"
-      shift 2
+      shift 2 || usage 1
       ;;
     --protoset)
       PROTOSET_FILENAME="$2"
-      shift 2
+      shift 2 || usage 1
       ;;
     --request)
       REQUEST_FILENAME="$2"
-      shift 2
+      shift 2 || usage 1
       ;;
     --plaintext)
       PLAINTEXT=1
       shift
+      ;;
+    --config-file)
+      CONFIG_FILE="$2"
+      shift 2 || usage 1
       ;;
     --help | -h) usage 0 ;;
     *) usage 1 ;;
@@ -57,55 +87,29 @@ done
 : "${PROTOSET_FILENAME?"Error: --protoset must be specified"}"
 : "${REQUEST_FILENAME?"Error: --request must be specified"}"
 : "${ENDPOINT_HOSTPORT?"Error: --endpoint-hostport not specified"}"
-: "${TEST_TOOLS_IMAGE?"Error: Test tools image URI not specified in TEST_TOOLS_IMAGE env var"}"
 
-REQ_JSON="$(<"${REQUEST_FILENAME}")"
 declare -r REPORT_FILE=ghz_report.json
-declare REPORT_FORMAT=pretty
-
-declare -a DOCKER_ARGS=(
-  "--rm"
-  "--interactive"
-  "--entrypoint=/bin/bash"
-  "--tmpfs=/work"
-  "--workdir=/work"
-)
-if [[ -n ${DOCKER_NETWORK} ]]; then
-  DOCKER_ARGS+=("--network=${DOCKER_NETWORK}")
-fi
+declare -r REPORT_FORMAT=pretty
 
 declare -a GHZ_ARGS=(
-  "--concurrency=10"
-  "--total=5000"
   "--call=${RPC}"
   "--format=${REPORT_FORMAT}"
+  "--data-file=${REQUEST_FILENAME}"
+  "--protoset=${PROTOSET_FILENAME}"
 )
-
 if [[ ${PLAINTEXT} -eq 1 ]]; then
   GHZ_ARGS+=("--insecure")
 fi
+if [[ -f ${CONFIG_FILE} ]]; then
+  GHZ_ARGS+=("--config=${CONFIG_FILE}")
+else
+  GHZ_ARGS+=(
+    "--concurrency=10"
+    "--total=5000"
+  )
+fi
 
-# declare -a GHZ_LINEAR_LOAD=(
-#   "--load-schedule=line"
-#   "--load-start=5"
-#   "--load-step=5"
-# )
-
-# declare -a GHZ_STEP_UP_RPS=(
-#   "--load-schedule=step"
-#   "--load-start=50"
-#   "--load-end=150"
-#   "--load-step=10"
-#   "--load-step-duration=5s"
-# )
-
-docker run "${DOCKER_ARGS[@]}" "${TEST_TOOLS_IMAGE}" -c "
-set -o errexit
-cat >rpc_request <<EOF
-${REQ_JSON}
-EOF
-cat /dev/stdin >protoset.pb
-ghz ${GHZ_ARGS[*]} --data-file=rpc_request --protoset protoset.pb ${ENDPOINT_HOSTPORT}
-" \
-  <"${PROTOSET_FILENAME}" \
-  >"${TEST_UNDECLARED_OUTPUTS_DIR}"/${REPORT_FILE}
+"${GHZ}" \
+  "${GHZ_ARGS[@]}" \
+  "${ENDPOINT_HOSTPORT}" \
+  >"${TEST_UNDECLARED_OUTPUTS_DIR}/${REPORT_FILE}"
diff --git a/testing/functionaltest-system/bazel/grpcurl_rpc_invoker b/testing/functionaltest-system/bazel/grpcurl_rpc_invoker
--- a/testing/functionaltest-system/bazel/grpcurl_rpc_invoker
+++ b/testing/functionaltest-system/bazel/grpcurl_rpc_invoker
@@ -2,8 +2,6 @@
 
 set -o errexit
 
-declare -i PLAINTEXT=0
-
 function usage() {
   local -r -i exitval=$1
   cat &>/dev/stderr <<USAGE
@@ -16,11 +14,27 @@ usage:
     --request <filename>            request.json filename
     --plaintext                     send plaintext request
 environment variables:
-    TEST_TOOLS_IMAGE                docker image uri for test tools
+    GRPCURL                         path to grpcurl executable (required)
 USAGE
   # shellcheck disable=SC2086
   exit ${exitval}
 }
+
+function check_app() {
+  declare -n _app=$1
+  if [[ -z ${_app} ]]; then
+    printf "env var [%s] is not set\n" "$1" &>/dev/stderr
+    exit 1
+  elif ! command -v "${_app}" >/dev/null; then
+    printf "%s command [%s] not found or not executable\n" "$1" "${_app}" &>/dev/stderr
+    exit 1
+  fi
+}
+
+check_app JQ
+check_app GRPCURL
+
+declare -i PLAINTEXT=0
 
 while [[ $# -gt 0 ]]; do
   case "$1" in
@@ -29,7 +43,6 @@ while [[ $# -gt 0 ]]; do
       shift 2
       ;;
     --docker-network)
-      DOCKER_NETWORK="$2"
       shift 2
       ;;
     --rpc)
@@ -57,42 +70,23 @@ done
 : "${REQUEST_FILENAME?"Error: --request must be specified"}"
 : "${ENDPOINT_HOSTPORT?"Error: --endpoint-hostport not specified"}"
 : "${PROTOSET_FILENAME?"Error: --protoset not specified"}"
-: "${TEST_TOOLS_IMAGE?"Error: Test tools image URI not specified in TEST_TOOLS_IMAGE env var"}"
 
-if [[ -z "${TEST_DATA_SOURCE}" ]]; then
-  TEST_DATA_SOURCE="$(docker volume create)"
-  export TEST_DATA_SOURCE
-  readonly TEST_DATA_SOURCE
-fi
-if [[ -z "${TEST_DATA_TARGET}" ]]; then
-  TEST_DATA_TARGET="/data"
-  export TEST_DATA_TARGET
-  readonly TEST_DATA_TARGET
-fi
-
-declare -a DOCKER_ARGS=(
-  "--rm"
-  "--interactive"
-  "--entrypoint=/bin/bash"
-  "--tmpfs=/work"
-  "--workdir=/work"
-  "--mount=type=volume,source=${TEST_DATA_SOURCE},target=${TEST_DATA_TARGET}"
+declare -a GRPCURL_ARGS=(
+  -d @
+  -protoset "${PROTOSET_FILENAME}"
 )
-if [[ -n ${DOCKER_NETWORK} ]]; then
-  DOCKER_ARGS+=("--network=${DOCKER_NETWORK}")
-fi
-
-declare -a GRPCURL_ARGS=()
 if [[ ${PLAINTEXT} -eq 1 ]]; then
   GRPCURL_ARGS+=("-plaintext")
 fi
+GRPCURL_ARGS+=(
+  "${ENDPOINT_HOSTPORT}"
+  "${RPC}"
+)
 
 GRPCURL_ERROR_TMPFILE="$(mktemp)"
 readonly GRPCURL_ERROR_TMPFILE
 
 set -o xtrace
-if ! docker run "${DOCKER_ARGS[@]}" "${TEST_TOOLS_IMAGE}" -c "
-grpcurl ${GRPCURL_ARGS[*]} -d @ -protoset '${TEST_DATA_TARGET}/protoset.pb' ${ENDPOINT_HOSTPORT} ${RPC} <'${TEST_DATA_TARGET}/req.json'
-" 2> "${GRPCURL_ERROR_TMPFILE}"; then
+if ! "${GRPCURL}" "${GRPCURL_ARGS[@]}" <"${REQUEST_FILENAME}" 2>"${GRPCURL_ERROR_TMPFILE}"; then
   cat "${GRPCURL_ERROR_TMPFILE}"
 fi
diff --git a/testing/functionaltest-system/bazel/rpc_diff_test_runner b/testing/functionaltest-system/bazel/rpc_diff_test_runner
--- a/testing/functionaltest-system/bazel/rpc_diff_test_runner
+++ b/testing/functionaltest-system/bazel/rpc_diff_test_runner
@@ -11,9 +11,7 @@ function usage() {
 usage:
   $0 <options>
     --rpc-invoker <filename>        image tarball or binary used to invoke rpc request
-    --rpc-invoker-type <filename>   recognized values: binary, image
     --endpoint-hostport <host:port> host:port string
-    --docker-network <name>         docker network
     --protoset <filename>           protobuf spec image file
     --rpc <rpc name>                rpc name
     --request <filename>            request.json filename
@@ -25,11 +23,24 @@ usage:
     --http-path <string>            path used with endpoint hostport
     --client-type <string>          client-type used to encrypt the request
 environment variables:
-    TEST_TOOLS_IMAGE                docker image uri for test tools
+    JQ                              path to jq executable (required)
 USAGE
   # shellcheck disable=SC2086
   exit ${exitval}
 }
+
+function check_app() {
+  declare -n _app=$1
+  if [[ -z ${_app} ]]; then
+    printf "env var [%s] is not set\n" "$1" &>/dev/stderr
+    exit 1
+  elif ! command -v "${_app}" >/dev/null; then
+    printf "%s command [%s] not found or not executable\n" "$1" "${_app}" &>/dev/stderr
+    exit 1
+  fi
+}
+
+check_app JQ
 
 while [[ $# -gt 0 ]]; do
   case "$1" in
@@ -38,7 +49,7 @@ while [[ $# -gt 0 ]]; do
       shift 2 || usage
       ;;
     --rpc-invoker-type)
-      RPC_INVOKER_TYPE="$2"
+      printf "Ignoring arg --rpc-invoker-type\n"
       shift 2 || usage
       ;;
     --endpoint-hostport)
@@ -46,7 +57,7 @@ while [[ $# -gt 0 ]]; do
       shift 2 || usage
       ;;
     --docker-network)
-      DOCKER_NETWORK="$2"
+      printf "Ignoring arg --docker-network\n"
       shift 2 || usage
       ;;
     --rpc)
@@ -100,8 +111,6 @@ done
 : "${GOLDEN_REPLY?"Error: --reply must be specified"}"
 : "${ENDPOINT_HOSTPORT?"Error: --endpoint-hostport not specified"}"
 : "${RPC_INVOKER?"Error: --rpc-invoker not specified"}"
-: "${RPC_INVOKER_TYPE?"Error: --rpc-invoker-type not specified"}"
-: "${TEST_TOOLS_IMAGE?"Error: Test tools image URI not specified in TEST_TOOLS_IMAGE env var"}"
 
 TMP_DIR="$(mktemp --directory)"
 readonly TMP_DIR
@@ -113,7 +122,9 @@ readonly TMP_FILTERED_REPLY="${TMP_DIR}/filtered_reply"
 readonly TMP_JQ_PRE_PROGRAM_FILENAME="${TMP_DIR}/pre_program.jq"
 readonly TMP_JQ_POST_PROGRAM_FILENAME="${TMP_DIR}/post_program.jq"
 readonly TMP_PROTOSET_FILENAME="${TMP_DIR}/protoset.pb"
+
 cp "${PROTOSET_FILENAME}" "${TMP_PROTOSET_FILENAME}"
+
 if [[ -s ${JQ_PRE_PROGRAM_FILENAME} ]]; then
   cp "${JQ_PRE_PROGRAM_FILENAME}" "${TMP_JQ_PRE_PROGRAM_FILENAME}"
 else
@@ -125,41 +136,14 @@ else
   printf '.\n' >"${TMP_JQ_POST_PROGRAM_FILENAME}"
 fi
 
-if [[ -z "${TEST_DATA_SOURCE}" ]]; then
-  TEST_DATA_SOURCE="$(docker volume create)"
-  export TEST_DATA_SOURCE
-  readonly TEST_DATA_SOURCE
-fi
-if [[ -z "${TEST_DATA_TARGET}" ]]; then
-  TEST_DATA_TARGET="/data"
-  export TEST_DATA_TARGET
-  readonly TEST_DATA_TARGET
-fi
-
-trap cleanup EXIT
 function cleanup() {
   local -r -i STATUS=$?
   if [[ ${STATUS} -eq 0 ]]; then
     rm -rf "${TMP_DIR}"
-    docker volume rm "${TEST_DATA_SOURCE}"
   fi
   exit ${STATUS}
 }
-
-declare -a DOCKER_ARGS=(
-  "--rm"
-  "--interactive"
-  "--entrypoint=/bin/bash"
-  "--mount=type=bind,source=/tmp,target=/tmp"
-  "--mount=type=volume,source=${TEST_DATA_SOURCE},target=${TEST_DATA_TARGET}"
-  "--tmpfs=/work"
-  "--workdir=/work"
-)
-
-declare -a RPC_INVOKER_DOCKER_ARGS=(
-  "--rm"
-  "--interactive"
-)
+trap cleanup EXIT
 
 declare -a RPC_INVOKER_ARGS=(
   --endpoint-hostport
@@ -167,15 +151,6 @@ declare -a RPC_INVOKER_ARGS=(
   --rpc
   "${RPC}"
 )
-
-if [[ -n ${DOCKER_NETWORK} ]]; then
-  DOCKER_ARGS+=("--network=${DOCKER_NETWORK}")
-  RPC_INVOKER_DOCKER_ARGS+=("--network=${DOCKER_NETWORK}")
-  RPC_INVOKER_ARGS+=(
-    --docker-network
-    "${DOCKER_NETWORK}"
-  )
-fi
 
 set -o xtrace
 
@@ -202,52 +177,23 @@ if [[ ${JQ_POST_SLURP} -eq 1 ]]; then
   JQ_POST_ARGS+=(--slurp)
 fi
 
-function copy_file_to_container() {
-  local -r INPUT_FILE="$1"
-  local -r OUTPUT_FILE="$2"
-
-  docker run "${DOCKER_ARGS[@]}" \
-    "${TEST_TOOLS_IMAGE}" \
-    -c "cat /dev/stdin > '${OUTPUT_FILE}'" \
-    <"${INPUT_FILE}"
-}
-
-copy_file_to_container "${TMP_JQ_PRE_PROGRAM_FILENAME}" "${TEST_DATA_TARGET}/pre-filter.jq"
-docker run "${DOCKER_ARGS[@]}" \
-  "${TEST_TOOLS_IMAGE}" \
-  -c "jq --exit-status --from-file '${TEST_DATA_TARGET}/pre-filter.jq'" \
+# Run pre-filter on request
+"${JQ}" --exit-status \
+  --from-file "${TMP_JQ_PRE_PROGRAM_FILENAME}" \
   <"${REQUEST_FILENAME}" \
   >"${TMP_FILTERED_REQUEST}"
 
-copy_file_to_container "${TMP_PROTOSET_FILENAME}" "${TEST_DATA_TARGET}/protoset.pb"
-copy_file_to_container "${TMP_FILTERED_REQUEST}" "${TEST_DATA_TARGET}/req.json"
-if [[ ${RPC_INVOKER_TYPE} == binary ]]; then
-  "${RPC_INVOKER}" \
-    --protoset "${TMP_PROTOSET_FILENAME}" \
-    --request "${TMP_FILTERED_REQUEST}" \
-    "${RPC_INVOKER_ARGS[@]}" \
-    >"${TMP_RAW_REPLY}"
-else
-  RPC_INVOKER_IMAGE="$(docker load -i "${RPC_INVOKER}" | sed -nr "s/^Loaded image: (.*)$/\1/p")"
-  readonly RPC_INVOKER_IMAGE
-  RAW_FILTERED_REQUEST="$(<"${TMP_FILTERED_REQUEST}")"
-  readonly RAW_FILTERED_REQUEST
-  RAW_PROTOSET="$(<"${PROTOSET_FILENAME}")"
-  readonly RAW_PROTOSET
+# Send request
+"${RPC_INVOKER}" \
+  --protoset "${TMP_PROTOSET_FILENAME}" \
+  --request "${TMP_FILTERED_REQUEST}" \
+  "${RPC_INVOKER_ARGS[@]}" \
+  >"${TMP_RAW_REPLY}"
 
-  docker run "${RPC_INVOKER_DOCKER_ARGS[@]}" "${RPC_INVOKER_IMAGE}" \
-    --protoset "${RAW_PROTOSET}" \
-    --request "${RAW_FILTERED_REQUEST}" \
-    "${RPC_INVOKER_ARGS[@]}" \
-    >"${TMP_RAW_REPLY}"
-fi
-
-# Check if TMP_RAW_REPLY is a valid json. If not, diff the raw reply without jq.
-if docker run "${DOCKER_ARGS[@]}" "${TEST_TOOLS_IMAGE}" -c "jq ${JQ_POST_ARGS[*]}" <"${TMP_RAW_REPLY}"; then
-  copy_file_to_container "${TMP_JQ_POST_PROGRAM_FILENAME}" "${TEST_DATA_TARGET}/post-filter.jq"
-  docker run "${DOCKER_ARGS[@]}" \
-    "${TEST_TOOLS_IMAGE}" \
-    -c "jq --from-file '${TEST_DATA_TARGET}/post-filter.jq' ${JQ_POST_ARGS[*]}" \
+# Check if TMP_RAW_REPLY is valid json. If not, diff the raw reply without jq.
+if "${JQ}" "${JQ_POST_ARGS[@]}" <"${TMP_RAW_REPLY}"; then
+  "${JQ}" --from-file "${TMP_JQ_POST_PROGRAM_FILENAME}" \
+    "${JQ_POST_ARGS[@]}" \
     <"${TMP_RAW_REPLY}" \
     >"${TMP_FILTERED_REPLY}"
 else
