internal: Try allowing code coverage on Kythe kokoro to upload to x20
Bug: b/298235919
Change-Id: I0fe956a03f2ca2b0c9ce078b9accb1a757787e35
GitOrigin-RevId: 1edee5608dad0c46867e72f9e8722945fb70e0a1

diff --git a/google_internal/kokoro/kythe_index_generation/run-kythe b/google_internal/kokoro/kythe_index_generation/run-kythe
--- a/google_internal/kokoro/kythe_index_generation/run-kythe
+++ b/google_internal/kokoro/kythe_index_generation/run-kythe
@@ -91,3 +91,7 @@ if [[ -v KOKORO_ARTIFACTS_DIR ]]; then
     "${KYTHE_OUTPUT_DIRECTORY}/${KYTHE_KZIP_NAME}" \
     "gs://kiwi-air-force-kythe-cross-references/commo-repo/${KYTHE_KZIP_NAME}"
 fi
+
+# Allow coverage to fail.
+"${WORKSPACE}"/builders/tools/bazel-debian coverage //... || true
+"${WORKSPACE}"/builders/tools/bazel-debian run //:collect-coverage || true
